
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finalhomework_db
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
redis:
  host: localhost
  port: 6379

loan-application:
  credit-limit-multiplier: 4


application:
  description: Final HomeWork Halil Can Irez
  version: 1.0.0


