version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:9379
    ports:
      - "8081:8081"